version: '3'

## NOTES:
# if you see ${SOME_VAR} in this file,
# these values are taken from .env file

#########################
#          DEV          #
#########################

services:

    nginx:
        image: nginx
        restart: "${RESTART_POLICIES}"
        ports:
            - "${NGINX_PORT}:80"
        links:
            - "symfony:symfony"
        volumes:
            - ".:/home/docker"
            - "./.docker/dev/dev.conf:/etc/nginx/conf.d/default.conf:ro"

    symfony:
        build:
            context: ./.docker/dev/
            args:
                - "DOCKER_USER=${DOCKER_USER}"
                - "GIT_USER_NAME=${GIT_USER_NAME}"
                - "GIT_USER_EMAIL=${GIT_USER_EMAIL}"
        image: symfony3_docker:dev
        restart: "${RESTART_POLICIES}"
        links:
            - "db:db"
        volumes:
            - ".:/home/docker"
            - "./.docker/dev/php.ini:/usr/local/etc/php/conf.d/custom.ini:ro"
        working_dir: "/home/docker"
        user: "${DOCKER_USER}"

    db:
        image: mysql
        restart: "${RESTART_POLICIES}"
        environment:
            - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
            - "MYSQL_USER=${MYSQL_USER}"
            - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
            - "MYSQL_DATABASE=${MYSQL_DATABASE}"
        ports:
            - "${MYSQL_PORT}:3306"
        volumes:
          - "./.data/db:/var/lib/mysql:Z"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: "${RESTART_POLICIES}"
        environment:
            - "PMA_HOST=db"
            - "PMA_USER=root"
            - "PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}"
        ports:
            - "${PMA_PORT}:80"
        depends_on:
            - "db"

    mailhog:
        image: mailhog/mailhog
        restart: "${RESTART_POLICIES}"
        ports:
            - "${MAILHOG_PORT}:8025"
            - "1025:1025"
        links:
            - "symfony:symfony"
